apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: tozastation-grpc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tozastation-grpc
    spec:
      containers:
        - name: grpc-server
          image: tozastation/grpc_training_golang:latest
          ports:
            - containerPort: 3001
          # env:
          #   - name: SQL_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: cloudsql
          #         key: username
          #   - name: SQL_PASS
          #     valueFrom:
          #       secretKeyRef:
          #         name: cloudsql
          #         key: password