apiVersion: v1
kind: Service
metadata:
  labels: 
    name: tozastation-grpc
  name: tozastation-service
spec:
  clusterIP: None
  ports:
    - name: tozastation-grpc
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: tozastation-grpc